print("Melting and Boiling Points of Alkanes")
print("Name \t\t Melting point(deg C) \t Boiling Point (deg C)")
print("Methane \t -162 \t\t\t -183")
print("Ethane \t\t -89 \t\t\t -172")
print("Propane \t -42 \t\t\t -188")
print("Butane  \t -0.5 \t\t\t -135 ")